spring:
  mongodb:
    uri: mongodb+srv://neemosapps_db_user:${DB_PASSWORD}@${DB_URL}
  ai:
    vectorstore:
      mongodb:
        collection-name: boy_store
        index-name: boy_index
        initialize-schema: true
    ollama:
      base-url: http://localhost:11434
      chat:
        frequency-penalty: 0
        model: qwen2.5:14b
      embedding:
        model: qwen3-embedding:8b
rag-resource:
  names:
   classpath:The Boy Story.pdf
