spring:
  ai:
    vectorstore:
      mongodb:
        collection-name: performance_store
        index-name: performance_index
        initialize-schema: true
    ollama:
      base-url: http://localhost:11434
      chat:
        frequency-penalty: 0
#        model: deepseek-coder:33b
        model: qwen2.5-coder:latest
      embedding:
        model: qwen3-embedding:8b

rag-resource:
  names:
    classpath:java-performance.pdf,
    classpath:jls25.pdf
  prompt-key: "java"